### ISSUE TITLE
Allow to disable images from 3-party server

### ISSUE THREAD

**Issue by gualse** [bouncepaw/mycomarkup#1]
Images form 3-party server can track hypha guests. We should allow to disable images from 3-party server.

**Comment by bouncepaw** [comment]
Well, yeah.

We may add the option some day, maybe. Perhaps.

**Comment by handlerug** [comment]
I can also suggest using CSP to prevent loading different kinds of 3rd-party content, including images and scripts.

**Comment by bouncepaw** [comment]
Moved to https://todo.sr.ht/~bouncepaw/mycomarkup/9
