### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by chekoopa** [bouncepaw/mycomarkup#11]
[Look, GFM has got footnotes!](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/)

We actually have [an idea of that](https://mycorrhiza.wiki/rev/9b9705f/idea/footnote_references), too. Let's implement it in similar fashion.

```
I like apples[[^about-apple]]. Let's bake charlotte pie[[^1]]!

notes {
  about-apple | { They are tasty.
But you need to be aware of worms. }
  1 | https://tasty-pies.org/charlotte.html
}
```

Notes:
- I've replaced `&` to `^`, like in [most](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html#inline-formatting) [of](https://www.markdownguide.org/extended-syntax/#footnotes) Markdown dialects.
- Also I've replaced `links` to `notes` to not mistake the idea with 'link aliases'. Possible alternatives are 'foot', 'footnotes', 'footer' etc.

## Design

Technically, it should be a two-pass process (scan for links, enumerate, and only then render both links and anchors). But we can force top-to-bottom declaration syntax and link-based enumeration. And also allow duplicate links (however, we would also need to implement anchor joining then).

Also, it is possible to implement this with a visitor, which would collect `notes` blocks, enumerate and replace footnote links with anchors (like, `name="footnote-1" href="#footer-about-apple"`) on-the-fly, and then we would use it to render a separate footnotes section. But seemingly inline mycolinks can't have names (thus, anchors to them), so we'd have to add them for return links.

Full Mycomarkup support in footnotes is seemingly possible, but I'd be careful with transclusions. Links and the section design is also a discussion point.

**Comment by handlerug** [comment]
@chekoopa Maybe be more specific with the block name? footnotes instead of notes, for example

**Comment by chekoopa** [comment]
> footnotes instead of notes, for example
Why not, but I feel that we should keep it shorter. Like, `img` instead of `image`.

**Comment by chekoopa** [comment]
Possible problems:
- marking or hiding missing footnotes, if we stick to an one-pass algorithm, because HTML renderer doesn't take any context besides of recursion level and block counter.
- hiding transclusion footlinks. But it seems that transclusions are rendered separately, so we could somehow invalidate these links with a special visitor.

**Comment by bouncepaw** [comment]
As for the linked idea, it's more of link aliases, as you've said on the wiki.

Footnotes seem cool.

> But seemingly inline mycolinks can't have names (thus, anchors to them), so we'd have to add them for return links.

Yes. What ids should they have? Something like `paragraph-3-link-4`?

> Full Mycomarkup support in footnotes is seemingly possible, but I'd be careful with transclusions.

We should limit it. And we should do the same with table cells and image descriptions too, to be honest! Currently, they support all of Mycomarkup.

> Links and the section design is also a discussion point.

Let's copy GitHub's design, it seems quite obvious.

> Maybe be more specific with the block name? footnotes instead of notes, for example

Agree

> Why not, but I feel that we should keep it shorter. Like, img instead of image.

image shortened to img is obvious. Footnotes shortened are notes is not, because there are various kinds of notes out there.

**Comment by bouncepaw** [comment]
Renamed the hypha on the wiki to _idea/link alilas_. Changed the top message to reflect that

**Comment by bouncepaw** [comment]
Moved to https://todo.sr.ht/~bouncepaw/mycomarkup/5
