### ISSUE TITLE
Mycomarkup subset for table cells

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycomarkup#17]
Did you know that table cells support all of Mycomarkup? You can even include a table in a table cells, which is not good.

| Block | Makes sense to be allowed?
|----|----
| Paragraph | ✅
| Inline link | ✅
| Image gallery | ✅
| Rocket link | ❓Perhaps, maybe?
| Codeblock | ❓Perhaps, maybe?
| List | ❓Perhaps, maybe?
| Quote | ❓Perhaps, maybe?
| Horizontal line | ❌Table cells have two horizontal lines already: top and bottom
| Heading | ❌There are heading cells already
| Table | ❌Nested tables are bad
| Transclusion | ❌Because transclusions support every block, thus making it possible to create a nested table.

**Comment by chekoopa** [comment]
It is much easier to keep that the way it is than create another subset, ain't it? No need to restrict users, moreover when these restrictions are implicit. All markup subsets are implicit here, help pages won't help, but warnings/hints would.

**Comment by bouncepaw** [comment]
It may be easier, but it is not right. Semantics 👍

**Comment by bouncepaw** [comment]
The question of what is inside a table cell is to be refined here: https://mycorrhiza.wiki/hypha/spec/blocks/table
