### ISSUE TITLE
Various image gallery layouts

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycomarkup#6]
Now, that's your image gallery:
```
img {
image 1
image 2
}
```

They are shown one below another. This is not enough.

From the very start I planned to have a way to specify the gallery's layout here:
```
img <layout> {
image 1
image 2
}
```

Some possible layouts:
* Content arrangement:
  * `default`
  * `grid`
  * `horizontal`
  * `carousel` (why?)
  * `text-to-the-right`
  * `tile`
* Gallery placement:
  * `stretch`
  * `right`
  * `left`

You can combine them like `grid right` (similar to [transclusion selectors](https://mycorrhiza.wiki/help/en/mycomarkup#Selector)).

**Comment by bouncepaw** [comment]
Left and right considered harmful.

I don't like them. When using ‘right’, I actually want to put the picture on the opposite side, not the right side. On RTL wikis it should be the left side, for example. 

Replace ‘right’ with ‘end’? ‘opposite’?

I need your suggestions.

**Comment by bouncepaw** [comment]
5 days have passed, no suggestions. I am about to cry. Whatever.

What about the grid layout? How many columns is it going to have? I think we need layouts grid2 and grid3 instead.

**Comment by YogurtTheHorse** [comment]
@bouncepaw I believe you can leave it to flexbox, and maybe give a glance on Bootstrap grid system

**Comment by chekoopa** [comment]
> Replace ‘right’ with ‘end’? ‘opposite’?

`start`, `end`, as in SVG. But arbitrary `left` and `right` are still desired IMHO.

**Comment by YogurtTheHorse** [comment]
@chekoopa Bootstrap 5 uses start and end btw

**Comment by bouncepaw** [comment]
`start` and `end` sound good, I choose them

**Comment by bouncepaw** [comment]
As of 2065460db6a1586880a80c9414320e7cf3dcee70, the layouts are there. I've added only a few of them, but it is easy to add many more if there is a need.

I'll close this issue once there is documentation for the layout syntax.

**Comment by bouncepaw** [comment]
Alright, the doc is there.

New issues shall be opened for new layout requests
