### ISSUE TITLE
Video and audio blocks

### ISSUE THREAD

**Issue by chekoopa** [bouncepaw/mycomarkup#7]
There's an idea to add a tag for video embedding. It would look similar to img, like this:

- From hypha: ```video { ../kittens | 100 { Are smol } }```
- From external link:  ```video { https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4 {Big Buck Bunny} }```
- From a streaming site (seems not possible easily, would require additional support) ```video { https://www.youtube.com/watch?v=Nq-q2USYetQ }```

**Comment by bouncepaw** [comment]
Yeah, cool. And `audio` too, right? One day, sure

As for the streaming sites, we have to decide which ones do we want to support? YouTube? Vimeo?

**Comment by bouncepaw** [comment]
Moved to https://todo.sr.ht/~bouncepaw/mycomarkup/3
